export type RecentInterestRow = {
  followUpDate: string;
  followUpDateCleaned: string;
  lead: string;
  campaignType: string;
  contactPerson: string;
  companyName: string;
  email: string;
  assignedTo: string;
  callResult: string;
  leadType: string;
  notes: string;
  phone: string;
  timezone: string;
};

export const recentInterestLeadOptions = [
  "Interested",
  "Qualified",
  "Follow Up",
  "Re-Engaged",
  "Hot Lead",
];

export const recentInterestCampaignOptions = [
  "Current Interest",
  "Reactivation",
  "Inbound",
  "Outbound",
  "Referral",
];

export const recentInterestAssigneeOptions = [
  "Hasib",
  "Nafis",
  "Asha",
  "Rafi",
  "Maliha",
  "Tanvir",
];

export const recentInterestCallResultOptions = [
  "Interested",
  "Call Lead Back",
  "No Answer",
  "Left Message",
  "Meeting Booked",
  "Qualified",
];

export const recentInterestLeadTypeOptions = [
  "Hot",
  "Warm",
  "Cold",
  "General",
  "Referral",
];

export const svgRecentInterestData: RecentInterestRow[] = [
  {
    followUpDate: "Apr 17, 2026",
    followUpDateCleaned: "2026-04-17",
    lead: "Interested",
    campaignType: "Current Interest",
    contactPerson: "Ariana West",
    companyName: "Northwind Labs",
    email: "ariana@northwind.io",
    timezone: "EST",
    assignedTo: "Hasib",
    callResult: "Meeting Booked",
    leadType: "Hot",
    notes: "Requested pricing deck and a follow-up call next week.",
    phone: "+1 415 221 0901",
  },
  {
    followUpDate: "Apr 18, 2026",
    followUpDateCleaned: "2026-04-18",
    lead: "Qualified",
    timezone: "EST",
    campaignType: "Inbound",
    contactPerson: "Rayan Chowdhury",
    companyName: "BluePeak Digital",
    email: "rayan@bluepeak.com",
    assignedTo: "Nafis",
    callResult: "Qualified",
    leadType: "Warm",
    notes: "Needs team access details before moving to proposal stage.",
    phone: "+1 202 555 0188",
  },
  {
    followUpDate: "Apr 19, 2026",
    followUpDateCleaned: "2026-04-19",
    timezone: "PST",
    lead: "Follow Up",
    campaignType: "Reactivation",
    contactPerson: "Nabila Ahmed",
    companyName: "BrightPath Health",
    email: "nabila@brightpath.health",
    assignedTo: "Maliha",
    callResult: "Call Lead Back",
    leadType: "Warm",
    notes: "Asked to reconnect after internal budget review on Friday.",
    phone: "+1 718 555 0133",
  },
  {
    followUpDate: "Apr 20, 2026",
    followUpDateCleaned: "2026-04-20",
    timezone: "PST",
    lead: "Re-Engaged",
    campaignType: "Referral",
    contactPerson: "Laura Chen",
    companyName: "Summit Freight",
    email: "laura@summitfreight.com",
    assignedTo: "Rafi",
    callResult: "Interested",
    leadType: "Referral",
    notes: "Referral source confirmed; waiting on warehouse volume estimate.",
    phone: "+1 206 555 0107",
  },
  {
    followUpDate: "Apr 22, 2026",
    followUpDateCleaned: "2026-04-22",
    timezone: "EST",
    lead: "Hot Lead",
    campaignType: "Outbound",
    contactPerson: "Marcus Bell",
    companyName: "Crestline Ops",
    email: "marcus@crestlineops.com",
    assignedTo: "Asha",
    callResult: "Interested",
    leadType: "Warm",
    notes: "Interested after outbound demo summary and requested a callback.",
    phone: "+1 312 555 0194",
  },
];

export const rm95RecentInterestData: RecentInterestRow[] = [
  {
    followUpDate: "Apr 16, 2026",
    followUpDateCleaned: "2026-04-16",
    timezone: "PST",
    lead: "Follow Up",
    campaignType: "Current Interest",
    contactPerson: "Jon Mercer",
    companyName: "PixelMint Studio",
    email: "jon@pixelmint.co",
    assignedTo: "Tanvir",
    callResult: "Left Message",
    leadType: "Cold",
    notes: "Voicemail left with offer summary and callback number.",
    phone: "+1 646 555 0177",
  },
  {
    followUpDate: "Apr 18, 2026",
    followUpDateCleaned: "2026-04-18",
    timezone: "CST",
    lead: "Qualified",
    campaignType: "Inbound",
    contactPerson: "Victor Lopez",
    companyName: "Transit Core",
    email: "victor@transitcore.es",
    assignedTo: "Nafis",
    callResult: "Meeting Booked",
    leadType: "Hot",
    notes: "Booked product walkthrough with ops director for Monday.",
    phone: "+34 91 555 0130",
  },
  {
    followUpDate: "Apr 17, 2026",
    followUpDateCleaned: "2026-04-17",
    timezone: "CST",
    lead: "Interested",
    campaignType: "Outbound",
    contactPerson: "Priya Sen",
    companyName: "Orbit Analytics",
    email: "priya@orbitanalytics.in",
    assignedTo: "Asha",
    callResult: "Call Lead Back",
    leadType: "Referral",
    notes: "Asked for a callback after discussing with procurement.",
    phone: "+91 80 5555 0198",
  },
  {
    followUpDate: "Apr 19, 2026",
    followUpDateCleaned: "2026-04-19",
    timezone: "PST",
    lead: "Hot Lead",
    campaignType: "Reactivation",
    contactPerson: "Hiro Tanaka",
    companyName: "Apex Imports",
    email: "hiro@apeximports.jp",
    assignedTo: "Hasib",
    callResult: "Interested",
    leadType: "Warm",
    notes: "Reopened conversation after seeing updated pricing offer.",
    phone: "+81 3 5550 0120",
  },
  {
    followUpDate: "Apr 20, 2026",
    followUpDateCleaned: "2026-04-20",
    timezone: "CST",
    lead: "Re-Engaged",
    campaignType: "Referral",
    contactPerson: "Elena Cruz",
    companyName: "Metro Vertex",
    email: "elena@metrovertex.com",
    assignedTo: "Rafi",
    callResult: "Meeting Booked",
    leadType: "Hot",
    notes: "Referral call converted into a booked follow-up with stakeholders.",
    phone: "+1 305 555 0162",
  },
];

export const bentonRecentInterestData: RecentInterestRow[] = [
  {
    followUpDate: "Apr 17, 2026",
    followUpDateCleaned: "2026-04-17",
    timezone: "EST",
    lead: "Follow Up",
    campaignType: "Current Interest",
    contactPerson: "Sadia Rahman",
    companyName: "Atlas Freight",
    email: "sadia@atlasfreight.com",
    assignedTo: "Tanvir",
    callResult: "Call Lead Back",
    leadType: "Warm",
    notes: "Requested a callback after checking fleet scheduling gaps.",
    phone: "+1 303 555 0192",
  },
  {
    followUpDate: "Apr 18, 2026",
    followUpDateCleaned: "2026-04-18",
    timezone: "CST",
    lead: "Re-Engaged",
    campaignType: "Reactivation",
    contactPerson: "Imran Ali",
    companyName: "Vertex Commerce",
    email: "imran@vertexcommerce.com",
    assignedTo: "Hasib",
    callResult: "Interested",
    leadType: "General",
    notes: "Returned after prior inactivity and asked for case studies.",
    phone: "+1 617 555 0114",
  },
  {
    followUpDate: "Apr 19, 2026",
    followUpDateCleaned: "2026-04-19",
    timezone: "PST",
    lead: "Qualified",
    campaignType: "Referral",
    contactPerson: "Grace Miller",
    companyName: "Harbor Ledger",
    email: "grace@harborledger.com",
    assignedTo: "Maliha",
    callResult: "Qualified",
    leadType: "Referral",
    notes: "Referral intro completed; solution fit confirmed on the call.",
    phone: "+1 212 555 0129",
  },
  {
    followUpDate: "Apr 21, 2026",
    followUpDateCleaned: "2026-04-21",
    timezone: "CST",
    lead: "Hot Lead",
    campaignType: "Inbound",
    contactPerson: "Sophia Turner",
    companyName: "Evercore Media",
    email: "sophia@evercoremedia.co.uk",
    assignedTo: "Rafi",
    callResult: "Meeting Booked",
    leadType: "Hot",
    notes: "Booked next-step demo with decision-makers from marketing.",
    phone: "+44 20 7946 0132",
  },
  {
    followUpDate: "Apr 22, 2026",
    followUpDateCleaned: "2026-04-22",
    timezone: "CST",
    lead: "Interested",
    campaignType: "Outbound",
    contactPerson: "Daniel Ross",
    companyName: "Lumen Works",
    email: "daniel@lumenworks.com",
    assignedTo: "Nafis",
    callResult: "Left Message",
    leadType: "General",
    notes: "Reached voicemail and left a concise recap of the offer.",
    phone: "+1 469 555 0141",
  },
];
